[package]
name = "jhapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oracle = "0.5.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
fern = "0.6.0"
log = "0.4.14"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.7"
chrono = "0.4.26"
jsonwebtoken = "8"

[dependencies.rocket]
version = "0.5.0-rc.3"
features = ["json"]
