#[allow(non_snake_case)]

use oracle::Row;
use oracle::pool::Pool;

use rocket::log::private::info;
use rocket::serde::json::Json;

use crate::product_data::structs::FetchParams;
use crate::product_data::structs::Product;

use crate::fetch_stores::get_stores;

use crate::ApiKey;

use crate::signing::decode_token_data;
use crate::utils::permissions::is_cost_perm;
use crate::utils::structs::APIErrors;

pub mod structs;


// TODO: Test performance of this function
pub async fn get_product(
    params: Json<FetchParams>,
    pool: &Pool,
    key: &ApiKey<'_>,
) -> Result<Vec<Product>, APIErrors> {
    
    // Empty params are not an error, but they should return an empty vec
    // TODO: Check if this is the best way to handle this
    if params.p_ref.is_none() && params.p_barcode.is_none() && params.p_id.is_none() {
        // vec![] is shorthand for Vec::new(), omitted for compile time optimization
        return Ok(Vec::new());
    }

    // Get username from token
    let username: String;
    
    match decode_token_data(key.0) {
        Some(data) => {
            username = data.USER_ID.unwrap().to_string();
        },
        None => {
            return Err(APIErrors::InvalideToken);
        }
    }

    
    let mut store_ids: Vec<String> = vec![];
    match get_stores(pool, username) {
        Ok(store_list) => {
            for i in store_list {
                store_ids.push(i.STORE_ID.unwrap());
            }
        }
        Err(e) => {
            info!("Error getting stores");
            return Err(e);
        }
    }

    // Helper function to get value from row and check if store is in store_ids
    fn get_value(store_ids: &Vec<String>, row: &Row, store_id: &str, column_name: &str) -> Option<String> {
        if store_ids.contains(&store_id.to_string()) {
            row.get(column_name).ok()
        } else {
            None
        }
    }

    let mut my_p_ref = "%";
    let mut my_p_barcode = "%";
    let mut my_p_id = "%";

    if let Some(p_ref) = &params.p_ref {
        my_p_ref = p_ref;
    }

    if let Some(p_barcode) = &params.p_barcode {
        my_p_barcode = p_barcode;
    }

    if let Some(p_id) = &params.p_id {
        my_p_id = p_id;
    }

    let conn = pool.get();
    if conn.is_err() {
        info!("Connection Error");
        return Err(APIErrors::DBError);
    }
    let conn = conn.unwrap();

    // Using column names made it hang on request -- On linux machine
    /* ITEM_ID, IS_ACTIVE, CAN_BE_SOLD, ITEM_DESC, ITEM_DESC_S, FOREIGN_ITEM_CODE, ITEM_CAT, ITEM_SUB_CAT, SALE_UNIT, UNIT_DESC, PACKING, CARD_OPEN_DATE, HS_CODE, COUNTRY, COUNTRY_DESC, SUPPLIER_ID, SUPPLIER_DESC, ITEM_MAIN_BARCODE, NATURE_ID, NATURE_DESC, TRADE_ID, TRADE_DESC, QTY_STORE_01, QTY_STORE_02, QTY_STORE_05, QTY_STORE_06, QTY_STORE_07, QTY_STORE_08, QTY_STORE_10, QTY_STORE_11, QTY_STORE_12, QTY_STORE_19, QTY_STORE_21, QTY_STORE_23, QTY_STORE_31, QTY_STORE_32, QTY_STORE_33, QTY_STORE_34, QTY_STORE_35, SALE_PRICE_NOTAX_STORE_01, SALE_PRICE_NOTAX_STORE_02, SALE_PRICE_NOTAX_STORE_05, SALE_PRICE_NOTAX_STORE_06, SALE_PRICE_NOTAX_STORE_08, SALE_PRICE_NOTAX_STORE_07, SALE_PRICE_NOTAX_STORE_31, SALE_PRICE_NOTAX_STORE_32, SALE_PRICE_NOTAX_STORE_33, SALE_PRICE_NOTAX_STORE_34, SALE_PRICE_NOTAX_STORE_35, FIRST_DISC_PER_STORE_01, FIRST_DISC_PER_STORE_02, FIRST_DISC_PER_STORE_05, FIRST_DISC_PER_STORE_06, FIRST_DISC_PER_STORE_07, FIRST_DISC_PER_STORE_08, FIRST_DISC_PER_STORE_31, FIRST_DISC_PER_STORE_32, FIRST_DISC_PER_STORE_33, FIRST_DISC_PER_STORE_34, FIRST_DISC_PER_STORE_35, SECOND_DISC_PER_STORE_01, SECOND_DISC_PER_STORE_02, SECOND_DISC_PER_STORE_05, SECOND_DISC_PER_STORE_06, SECOND_DISC_PER_STORE_07, SECOND_DISC_PER_STORE_08, SECOND_DISC_PER_STORE_31, SECOND_DISC_PER_STORE_32, SECOND_DISC_PER_STORE_33, SECOND_DISC_PER_STORE_34, SECOND_DISC_PER_STORE_35 */

    // Store start time
    // let start = Instant::now();

    // multiple forms of query based on params

    // TODO: Fix error handling on the query

    let mut stmt;
    let rows;

    // TODO: try a match block here
    if my_p_ref == "%" && my_p_barcode != "%" {
        //println!("a");
        stmt = conn.statement("SELECT ITEM_ID, IS_ACTIVE, CAN_BE_SOLD, ITEM_DESC, ITEM_DESC_S, FOREIGN_ITEM_CODE, ITEM_CAT, ITEM_SUB_CAT, SALE_UNIT, UNIT_DESC, PACKING, CARD_OPEN_DATE, HS_CODE, COUNTRY, COUNTRY_DESC, SUPPLIER_ID, SUPPLIER_DESC, ITEM_MAIN_BARCODE, NATURE_ID, NATURE_DESC, TRADE_ID, TRADE_DESC, QTY_STORE_01, QTY_STORE_02, QTY_STORE_05, QTY_STORE_06, QTY_STORE_07, QTY_STORE_08, QTY_STORE_09, QTY_STORE_10, QTY_STORE_11, QTY_STORE_12, QTY_STORE_19, QTY_STORE_21, QTY_STORE_23, QTY_STORE_31, QTY_STORE_32, QTY_STORE_33, QTY_STORE_34, QTY_STORE_35, SALE_PRICE_NOTAX_STORE_01, SALE_PRICE_NOTAX_STORE_02, SALE_PRICE_NOTAX_STORE_05, SALE_PRICE_NOTAX_STORE_06, SALE_PRICE_NOTAX_STORE_08, SALE_PRICE_NOTAX_STORE_09, SALE_PRICE_NOTAX_STORE_07, SALE_PRICE_NOTAX_STORE_31, SALE_PRICE_NOTAX_STORE_32, SALE_PRICE_NOTAX_STORE_33, SALE_PRICE_NOTAX_STORE_34, SALE_PRICE_NOTAX_STORE_35, FIRST_DISC_PER_STORE_01, FIRST_DISC_PER_STORE_02, FIRST_DISC_PER_STORE_05, FIRST_DISC_PER_STORE_06, FIRST_DISC_PER_STORE_07, FIRST_DISC_PER_STORE_08, FIRST_DISC_PER_STORE_09, FIRST_DISC_PER_STORE_31, FIRST_DISC_PER_STORE_32, FIRST_DISC_PER_STORE_33, FIRST_DISC_PER_STORE_34, FIRST_DISC_PER_STORE_35, SECOND_DISC_PER_STORE_01, SECOND_DISC_PER_STORE_02, SECOND_DISC_PER_STORE_05, SECOND_DISC_PER_STORE_06, SECOND_DISC_PER_STORE_07, SECOND_DISC_PER_STORE_08, SECOND_DISC_PER_STORE_09, SECOND_DISC_PER_STORE_31, SECOND_DISC_PER_STORE_32, SECOND_DISC_PER_STORE_33, SECOND_DISC_PER_STORE_34, SECOND_DISC_PER_STORE_35, T_AVE_COST FROM ODBC_JHC.JHC_INVDATA WHERE BARCODE_LISTED LIKE '%' || :barcode || '%' AND ITEM_ID LIKE :id").build().unwrap();
        rows = stmt.query(&[&my_p_barcode, &my_p_id]).unwrap();
        
    } else if my_p_ref != "%" && my_p_barcode == "%" {
        //println!("b");
        stmt = conn.statement("SELECT ITEM_ID, IS_ACTIVE, CAN_BE_SOLD, ITEM_DESC, ITEM_DESC_S, FOREIGN_ITEM_CODE, ITEM_CAT, ITEM_SUB_CAT, SALE_UNIT, UNIT_DESC, PACKING, CARD_OPEN_DATE, HS_CODE, COUNTRY, COUNTRY_DESC, SUPPLIER_ID, SUPPLIER_DESC, ITEM_MAIN_BARCODE, NATURE_ID, NATURE_DESC, TRADE_ID, TRADE_DESC, QTY_STORE_01, QTY_STORE_02, QTY_STORE_05, QTY_STORE_06, QTY_STORE_07, QTY_STORE_08, QTY_STORE_09, QTY_STORE_10, QTY_STORE_11, QTY_STORE_12, QTY_STORE_19, QTY_STORE_21, QTY_STORE_23, QTY_STORE_31, QTY_STORE_32, QTY_STORE_33, QTY_STORE_34, QTY_STORE_35, SALE_PRICE_NOTAX_STORE_01, SALE_PRICE_NOTAX_STORE_02, SALE_PRICE_NOTAX_STORE_05, SALE_PRICE_NOTAX_STORE_06, SALE_PRICE_NOTAX_STORE_08, SALE_PRICE_NOTAX_STORE_09, SALE_PRICE_NOTAX_STORE_07, SALE_PRICE_NOTAX_STORE_31, SALE_PRICE_NOTAX_STORE_32, SALE_PRICE_NOTAX_STORE_33, SALE_PRICE_NOTAX_STORE_34, SALE_PRICE_NOTAX_STORE_35, FIRST_DISC_PER_STORE_01, FIRST_DISC_PER_STORE_02, FIRST_DISC_PER_STORE_05, FIRST_DISC_PER_STORE_06, FIRST_DISC_PER_STORE_07, FIRST_DISC_PER_STORE_08, FIRST_DISC_PER_STORE_09, FIRST_DISC_PER_STORE_31, FIRST_DISC_PER_STORE_32, FIRST_DISC_PER_STORE_33, FIRST_DISC_PER_STORE_34, FIRST_DISC_PER_STORE_35, SECOND_DISC_PER_STORE_01, SECOND_DISC_PER_STORE_02, SECOND_DISC_PER_STORE_05, SECOND_DISC_PER_STORE_06, SECOND_DISC_PER_STORE_07, SECOND_DISC_PER_STORE_08, SECOND_DISC_PER_STORE_09, SECOND_DISC_PER_STORE_31, SECOND_DISC_PER_STORE_32, SECOND_DISC_PER_STORE_33, SECOND_DISC_PER_STORE_34, SECOND_DISC_PER_STORE_35, T_AVE_COST FROM ODBC_JHC.JHC_INVDATA WHERE FOREIGN_ITEM_CODE LIKE :ref AND ITEM_ID LIKE :id").build().unwrap();
        rows = stmt.query(&[&my_p_ref, &my_p_id]).unwrap();
        
    } else if my_p_ref == "%" && my_p_barcode == "%" {
        //println!("c");
        stmt = conn.statement("SELECT ITEM_ID, IS_ACTIVE, CAN_BE_SOLD, ITEM_DESC, ITEM_DESC_S, FOREIGN_ITEM_CODE, ITEM_CAT, ITEM_SUB_CAT, SALE_UNIT, UNIT_DESC, PACKING, CARD_OPEN_DATE, HS_CODE, COUNTRY, COUNTRY_DESC, SUPPLIER_ID, SUPPLIER_DESC, ITEM_MAIN_BARCODE, NATURE_ID, NATURE_DESC, TRADE_ID, TRADE_DESC, QTY_STORE_01, QTY_STORE_02, QTY_STORE_05, QTY_STORE_06, QTY_STORE_07, QTY_STORE_08, QTY_STORE_09, QTY_STORE_10, QTY_STORE_11, QTY_STORE_12, QTY_STORE_19, QTY_STORE_21, QTY_STORE_23, QTY_STORE_31, QTY_STORE_32, QTY_STORE_33, QTY_STORE_34, QTY_STORE_35, SALE_PRICE_NOTAX_STORE_01, SALE_PRICE_NOTAX_STORE_02, SALE_PRICE_NOTAX_STORE_05, SALE_PRICE_NOTAX_STORE_06, SALE_PRICE_NOTAX_STORE_08, SALE_PRICE_NOTAX_STORE_09, SALE_PRICE_NOTAX_STORE_07, SALE_PRICE_NOTAX_STORE_31, SALE_PRICE_NOTAX_STORE_32, SALE_PRICE_NOTAX_STORE_33, SALE_PRICE_NOTAX_STORE_34, SALE_PRICE_NOTAX_STORE_35, FIRST_DISC_PER_STORE_01, FIRST_DISC_PER_STORE_02, FIRST_DISC_PER_STORE_05, FIRST_DISC_PER_STORE_06, FIRST_DISC_PER_STORE_07, FIRST_DISC_PER_STORE_08, FIRST_DISC_PER_STORE_09, FIRST_DISC_PER_STORE_31, FIRST_DISC_PER_STORE_32, FIRST_DISC_PER_STORE_33, FIRST_DISC_PER_STORE_34, FIRST_DISC_PER_STORE_35, SECOND_DISC_PER_STORE_01, SECOND_DISC_PER_STORE_02, SECOND_DISC_PER_STORE_05, SECOND_DISC_PER_STORE_06, SECOND_DISC_PER_STORE_07, SECOND_DISC_PER_STORE_08, SECOND_DISC_PER_STORE_09, SECOND_DISC_PER_STORE_31, SECOND_DISC_PER_STORE_32, SECOND_DISC_PER_STORE_33, SECOND_DISC_PER_STORE_34, SECOND_DISC_PER_STORE_35, T_AVE_COST FROM ODBC_JHC.JHC_INVDATA WHERE ITEM_ID LIKE :id").build().unwrap();
        rows = stmt.query(&[&my_p_id]).unwrap();
        
    } else {
        //println!("d");
        stmt = conn.statement("SELECT ITEM_ID, IS_ACTIVE, CAN_BE_SOLD, ITEM_DESC, ITEM_DESC_S, FOREIGN_ITEM_CODE, ITEM_CAT, ITEM_SUB_CAT, SALE_UNIT, UNIT_DESC, PACKING, CARD_OPEN_DATE, HS_CODE, COUNTRY, COUNTRY_DESC, SUPPLIER_ID, SUPPLIER_DESC, ITEM_MAIN_BARCODE, NATURE_ID, NATURE_DESC, TRADE_ID, TRADE_DESC, QTY_STORE_01, QTY_STORE_02, QTY_STORE_05, QTY_STORE_06, QTY_STORE_07, QTY_STORE_08, QTY_STORE_09, QTY_STORE_10, QTY_STORE_11, QTY_STORE_12, QTY_STORE_19, QTY_STORE_21, QTY_STORE_23, QTY_STORE_31, QTY_STORE_32, QTY_STORE_33, QTY_STORE_34, QTY_STORE_35, SALE_PRICE_NOTAX_STORE_01, SALE_PRICE_NOTAX_STORE_02, SALE_PRICE_NOTAX_STORE_05, SALE_PRICE_NOTAX_STORE_06, SALE_PRICE_NOTAX_STORE_08, SALE_PRICE_NOTAX_STORE_09, SALE_PRICE_NOTAX_STORE_07, SALE_PRICE_NOTAX_STORE_31, SALE_PRICE_NOTAX_STORE_32, SALE_PRICE_NOTAX_STORE_33, SALE_PRICE_NOTAX_STORE_34, SALE_PRICE_NOTAX_STORE_35, FIRST_DISC_PER_STORE_01, FIRST_DISC_PER_STORE_02, FIRST_DISC_PER_STORE_05, FIRST_DISC_PER_STORE_06, FIRST_DISC_PER_STORE_07, FIRST_DISC_PER_STORE_08, FIRST_DISC_PER_STORE_09, FIRST_DISC_PER_STORE_31, FIRST_DISC_PER_STORE_32, FIRST_DISC_PER_STORE_33, FIRST_DISC_PER_STORE_34, FIRST_DISC_PER_STORE_35, SECOND_DISC_PER_STORE_01, SECOND_DISC_PER_STORE_02, SECOND_DISC_PER_STORE_05, SECOND_DISC_PER_STORE_06, SECOND_DISC_PER_STORE_07, SECOND_DISC_PER_STORE_08, SECOND_DISC_PER_STORE_09, SECOND_DISC_PER_STORE_31, SECOND_DISC_PER_STORE_32, SECOND_DISC_PER_STORE_33, SECOND_DISC_PER_STORE_34, SECOND_DISC_PER_STORE_35, T_AVE_COST FROM ODBC_JHC.JHC_INVDATA WHERE FOREIGN_ITEM_CODE LIKE :ref AND BARCODE_LISTED LIKE '%' || :barcode || '%' AND ITEM_ID LIKE :id").build().unwrap();
        rows = stmt.query(&[&my_p_ref, &my_p_barcode, &my_p_id]).unwrap();
    }

    // let mut stmt = conn.statement("SELECT ITEM_ID, IS_ACTIVE, CAN_BE_SOLD, ITEM_DESC, ITEM_DESC_S, FOREIGN_ITEM_CODE, ITEM_CAT, ITEM_SUB_CAT, SALE_UNIT, UNIT_DESC, PACKING, CARD_OPEN_DATE, HS_CODE, COUNTRY, COUNTRY_DESC, SUPPLIER_ID, SUPPLIER_DESC, ITEM_MAIN_BARCODE, NATURE_ID, NATURE_DESC, TRADE_ID, TRADE_DESC, QTY_STORE_01, QTY_STORE_02, QTY_STORE_05, QTY_STORE_06, QTY_STORE_07, QTY_STORE_08, QTY_STORE_09, QTY_STORE_10, QTY_STORE_11, QTY_STORE_12, QTY_STORE_19, QTY_STORE_21, QTY_STORE_23, QTY_STORE_31, QTY_STORE_32, QTY_STORE_33, QTY_STORE_34, QTY_STORE_35, SALE_PRICE_NOTAX_STORE_01, SALE_PRICE_NOTAX_STORE_02, SALE_PRICE_NOTAX_STORE_05, SALE_PRICE_NOTAX_STORE_06, SALE_PRICE_NOTAX_STORE_08, SALE_PRICE_NOTAX_STORE_09, SALE_PRICE_NOTAX_STORE_07, SALE_PRICE_NOTAX_STORE_31, SALE_PRICE_NOTAX_STORE_32, SALE_PRICE_NOTAX_STORE_33, SALE_PRICE_NOTAX_STORE_34, SALE_PRICE_NOTAX_STORE_35, FIRST_DISC_PER_STORE_01, FIRST_DISC_PER_STORE_02, FIRST_DISC_PER_STORE_05, FIRST_DISC_PER_STORE_06, FIRST_DISC_PER_STORE_07, FIRST_DISC_PER_STORE_08, FIRST_DISC_PER_STORE_09, FIRST_DISC_PER_STORE_31, FIRST_DISC_PER_STORE_32, FIRST_DISC_PER_STORE_33, FIRST_DISC_PER_STORE_34, FIRST_DISC_PER_STORE_35, SECOND_DISC_PER_STORE_01, SECOND_DISC_PER_STORE_02, SECOND_DISC_PER_STORE_05, SECOND_DISC_PER_STORE_06, SECOND_DISC_PER_STORE_07, SECOND_DISC_PER_STORE_08, SECOND_DISC_PER_STORE_09, SECOND_DISC_PER_STORE_31, SECOND_DISC_PER_STORE_32, SECOND_DISC_PER_STORE_33, SECOND_DISC_PER_STORE_34, SECOND_DISC_PER_STORE_35, T_AVE_COST FROM ODBC_JHC.JHC_INVDATA WHERE FOREIGN_ITEM_CODE LIKE :ref AND ITEM_MAIN_BARCODE LIKE :barcode AND ITEM_ID LIKE :id").build()?;
    // let mut stmt = conn.statement("SELECT ITEM_ID, IS_ACTIVE, CAN_BE_SOLD, ITEM_DESC, ITEM_DESC_S, FOREIGN_ITEM_CODE, ITEM_CAT, ITEM_SUB_CAT, SALE_UNIT, UNIT_DESC, PACKING, CARD_OPEN_DATE, HS_CODE, COUNTRY, COUNTRY_DESC, SUPPLIER_ID, SUPPLIER_DESC, ITEM_MAIN_BARCODE, NATURE_ID, NATURE_DESC, TRADE_ID, TRADE_DESC, QTY_STORE_01, QTY_STORE_02, QTY_STORE_05, QTY_STORE_06, QTY_STORE_07, QTY_STORE_08, QTY_STORE_09, QTY_STORE_10, QTY_STORE_11, QTY_STORE_12, QTY_STORE_19, QTY_STORE_21, QTY_STORE_23, QTY_STORE_31, QTY_STORE_32, QTY_STORE_33, QTY_STORE_34, QTY_STORE_35, SALE_PRICE_NOTAX_STORE_01, SALE_PRICE_NOTAX_STORE_02, SALE_PRICE_NOTAX_STORE_05, SALE_PRICE_NOTAX_STORE_06, SALE_PRICE_NOTAX_STORE_08, SALE_PRICE_NOTAX_STORE_09, SALE_PRICE_NOTAX_STORE_07, SALE_PRICE_NOTAX_STORE_31, SALE_PRICE_NOTAX_STORE_32, SALE_PRICE_NOTAX_STORE_33, SALE_PRICE_NOTAX_STORE_34, SALE_PRICE_NOTAX_STORE_35, FIRST_DISC_PER_STORE_01, FIRST_DISC_PER_STORE_02, FIRST_DISC_PER_STORE_05, FIRST_DISC_PER_STORE_06, FIRST_DISC_PER_STORE_07, FIRST_DISC_PER_STORE_08, FIRST_DISC_PER_STORE_09, FIRST_DISC_PER_STORE_31, FIRST_DISC_PER_STORE_32, FIRST_DISC_PER_STORE_33, FIRST_DISC_PER_STORE_34, FIRST_DISC_PER_STORE_35, SECOND_DISC_PER_STORE_01, SECOND_DISC_PER_STORE_02, SECOND_DISC_PER_STORE_05, SECOND_DISC_PER_STORE_06, SECOND_DISC_PER_STORE_07, SECOND_DISC_PER_STORE_08, SECOND_DISC_PER_STORE_09, SECOND_DISC_PER_STORE_31, SECOND_DISC_PER_STORE_32, SECOND_DISC_PER_STORE_33, SECOND_DISC_PER_STORE_34, SECOND_DISC_PER_STORE_35, T_AVE_COST FROM ODBC_JHC.JHC_INVDATA WHERE FOREIGN_ITEM_CODE LIKE :ref AND (ITEM_MAIN_BARCODE = :barcode OR BARCODE_LISTED LIKE '%' || :barcode || '%') AND ITEM_ID LIKE :id").build()?;

    // println!("Query Time: {:?}", start.elapsed());

    let mut products: Vec<Product> = Vec::new();

    for row_result in rows {
        if row_result.is_err() {
            info!("Row Error");
            return Err(APIErrors::DBError);
        }
        let row = row_result.unwrap();
        products.push(Product {
            ITEM_ID: row.get("ITEM_ID").unwrap(),
            IS_ACTIVE: row.get("IS_ACTIVE").unwrap(),
            CAN_BE_SOLD: row.get("CAN_BE_SOLD").unwrap(),
            ITEM_DESC: row.get("ITEM_DESC").unwrap(),
            ITEM_DESC_S: row.get("ITEM_DESC_S").unwrap(),
            FOREIGN_ITEM_CODE: row.get("FOREIGN_ITEM_CODE").unwrap(),
            ITEM_CAT: row.get("ITEM_CAT").unwrap(),
            ITEM_SUB_CAT: row.get("ITEM_SUB_CAT").unwrap(),
            SALE_UNIT: row.get("SALE_UNIT").unwrap(),
            UNIT_DESC: row.get("UNIT_DESC").unwrap(),
            PACKING: row.get("PACKING").unwrap(),
            CARD_OPEN_DATE: row.get("CARD_OPEN_DATE").unwrap(),
            HS_CODE: row.get("HS_CODE").unwrap(),
            COUNTRY: row.get("COUNTRY").unwrap(),
            COUNTRY_DESC: row.get("COUNTRY_DESC").unwrap(),
            SUPPLIER_ID: row.get("SUPPLIER_ID").unwrap(),
            SUPPLIER_DESC: row.get("SUPPLIER_DESC").unwrap(),
            ITEM_MAIN_BARCODE: row.get("ITEM_MAIN_BARCODE").unwrap(),
            NATURE_ID: row.get("NATURE_ID").unwrap(),
            NATURE_DESC: row.get("NATURE_DESC").unwrap(),
            TRADE_ID: row.get("TRADE_ID").unwrap(),
            TRADE_DESC: row.get("TRADE_DESC").unwrap(),
            QTY_STORE_01: get_value(&store_ids, &row, "01", "QTY_STORE_01"),
            QTY_STORE_02: get_value(&store_ids, &row, "02", "QTY_STORE_02"),
            QTY_STORE_05: get_value(&store_ids, &row, "05", "QTY_STORE_05"),
            QTY_STORE_06: get_value(&store_ids, &row, "06", "QTY_STORE_06"),
            QTY_STORE_07: get_value(&store_ids, &row, "07", "QTY_STORE_07"),
            QTY_STORE_08: get_value(&store_ids, &row, "08", "QTY_STORE_08"),
            QTY_STORE_09: get_value(&store_ids, &row, "09", "QTY_STORE_09"),
            QTY_STORE_10: get_value(&store_ids, &row, "10", "QTY_STORE_10"),
            QTY_STORE_11: get_value(&store_ids, &row, "11", "QTY_STORE_11"),
            QTY_STORE_12: get_value(&store_ids, &row, "12", "QTY_STORE_12"),
            QTY_STORE_19: get_value(&store_ids, &row, "19", "QTY_STORE_19"),
            QTY_STORE_21: get_value(&store_ids, &row, "21", "QTY_STORE_21"),
            QTY_STORE_23: get_value(&store_ids, &row, "23", "QTY_STORE_23"),
            QTY_STORE_31: get_value(&store_ids, &row, "31", "QTY_STORE_31"),
            QTY_STORE_32: get_value(&store_ids, &row, "32", "QTY_STORE_32"),
            QTY_STORE_33: get_value(&store_ids, &row, "33", "QTY_STORE_33"),
            QTY_STORE_34: get_value(&store_ids, &row, "34", "QTY_STORE_34"),
            QTY_STORE_35: get_value(&store_ids, &row, "35", "QTY_STORE_35"),
            SALE_PRICE_NOTAX_STORE_01: get_value(&store_ids, &row, "01", "SALE_PRICE_NOTAX_STORE_01"),
            SALE_PRICE_NOTAX_STORE_02: get_value(&store_ids, &row, "02", "SALE_PRICE_NOTAX_STORE_02"),
            SALE_PRICE_NOTAX_STORE_05: get_value(&store_ids, &row, "05", "SALE_PRICE_NOTAX_STORE_05"),
            SALE_PRICE_NOTAX_STORE_06: get_value(&store_ids, &row, "06", "SALE_PRICE_NOTAX_STORE_06"),
            SALE_PRICE_NOTAX_STORE_08: get_value(&store_ids, &row, "08", "SALE_PRICE_NOTAX_STORE_08"),
            SALE_PRICE_NOTAX_STORE_09: get_value(&store_ids, &row, "09", "SALE_PRICE_NOTAX_STORE_09"),
            SALE_PRICE_NOTAX_STORE_07: get_value(&store_ids, &row, "07", "SALE_PRICE_NOTAX_STORE_07"),
            SALE_PRICE_NOTAX_STORE_31: get_value(&store_ids, &row, "31", "SALE_PRICE_NOTAX_STORE_31"),
            SALE_PRICE_NOTAX_STORE_32: get_value(&store_ids, &row, "32", "SALE_PRICE_NOTAX_STORE_32"),
            SALE_PRICE_NOTAX_STORE_33: get_value(&store_ids, &row, "33", "SALE_PRICE_NOTAX_STORE_33"),
            SALE_PRICE_NOTAX_STORE_34: get_value(&store_ids, &row, "34", "SALE_PRICE_NOTAX_STORE_34"),
            SALE_PRICE_NOTAX_STORE_35: get_value(&store_ids, &row, "35", "SALE_PRICE_NOTAX_STORE_35"),
            FIRST_DISC_PER_STORE_01: get_value(&store_ids, &row, "01", "FIRST_DISC_PER_STORE_01"),
            FIRST_DISC_PER_STORE_02: get_value(&store_ids, &row, "02", "FIRST_DISC_PER_STORE_02"),
            FIRST_DISC_PER_STORE_05: get_value(&store_ids, &row, "05", "FIRST_DISC_PER_STORE_05"),
            FIRST_DISC_PER_STORE_06: get_value(&store_ids, &row, "06", "FIRST_DISC_PER_STORE_06"),
            FIRST_DISC_PER_STORE_07: get_value(&store_ids, &row, "07", "FIRST_DISC_PER_STORE_07"),
            FIRST_DISC_PER_STORE_08: get_value(&store_ids, &row, "08", "FIRST_DISC_PER_STORE_08"),
            FIRST_DISC_PER_STORE_09: get_value(&store_ids, &row, "09", "FIRST_DISC_PER_STORE_09"),
            FIRST_DISC_PER_STORE_31: get_value(&store_ids, &row, "31", "FIRST_DISC_PER_STORE_31"),
            FIRST_DISC_PER_STORE_32: get_value(&store_ids, &row, "32", "FIRST_DISC_PER_STORE_32"),
            FIRST_DISC_PER_STORE_33: get_value(&store_ids, &row, "33", "FIRST_DISC_PER_STORE_33"),
            FIRST_DISC_PER_STORE_34: get_value(&store_ids, &row, "34", "FIRST_DISC_PER_STORE_34"),
            FIRST_DISC_PER_STORE_35: get_value(&store_ids, &row, "35", "FIRST_DISC_PER_STORE_35"),
            SECOND_DISC_PER_STORE_01: get_value(&store_ids, &row, "01", "SECOND_DISC_PER_STORE_01"),
            SECOND_DISC_PER_STORE_02: get_value(&store_ids, &row, "02", "SECOND_DISC_PER_STORE_02"),
            SECOND_DISC_PER_STORE_05: get_value(&store_ids, &row, "05", "SECOND_DISC_PER_STORE_05"),
            SECOND_DISC_PER_STORE_06: get_value(&store_ids, &row, "06", "SECOND_DISC_PER_STORE_06"),
            SECOND_DISC_PER_STORE_07: get_value(&store_ids, &row, "07", "SECOND_DISC_PER_STORE_07"),
            SECOND_DISC_PER_STORE_08: get_value(&store_ids, &row, "08", "SECOND_DISC_PER_STORE_08"),
            SECOND_DISC_PER_STORE_09: get_value(&store_ids, &row, "09", "SECOND_DISC_PER_STORE_09"),
            SECOND_DISC_PER_STORE_31: get_value(&store_ids, &row, "31", "SECOND_DISC_PER_STORE_31"),
            SECOND_DISC_PER_STORE_32: get_value(&store_ids, &row, "32", "SECOND_DISC_PER_STORE_32"),
            SECOND_DISC_PER_STORE_33: get_value(&store_ids, &row, "33", "SECOND_DISC_PER_STORE_33"),
            SECOND_DISC_PER_STORE_34: get_value(&store_ids, &row, "34", "SECOND_DISC_PER_STORE_34"),
            SECOND_DISC_PER_STORE_35: get_value(&store_ids, &row, "35", "SECOND_DISC_PER_STORE_35"),
            T_AVE_COST: if is_cost_perm(key, pool) {
                row.get("T_AVE_COST").unwrap()
            } else {
                None
            },
        });
    }

    info!("Products Count: {:?}", products.len());

    Ok(products)
}

/*
pub async fn get_product_pi(
    params: Json<FetchParams>,
    pool: &Pool,
    _key: &ApiKey<'_>,
) -> Result<Vec<Product>> {
    if params.p_ref.is_none() && params.p_barcode.is_none() && params.p_id.is_none() {
        return Ok(vec![]);
    }

    let mut my_p_ref = "%";
    let mut my_p_barcode = "%";
    let mut my_p_id = "%";

    if let Some(p_ref) = &params.p_ref {
        my_p_ref = p_ref;
    }

    if let Some(p_barcode) = &params.p_barcode {
        my_p_barcode = p_barcode;
    }

    if let Some(p_id) = &params.p_id {
        my_p_id = p_id;
    }

    let conn = pool.get()?;

    // Using column names made it hang on request -- On linux machine
    /* ITEM_ID, IS_ACTIVE, CAN_BE_SOLD, ITEM_DESC, ITEM_DESC_S, FOREIGN_ITEM_CODE, ITEM_CAT, ITEM_SUB_CAT, SALE_UNIT, UNIT_DESC, PACKING, CARD_OPEN_DATE, HS_CODE, COUNTRY, COUNTRY_DESC, SUPPLIER_ID, SUPPLIER_DESC, ITEM_MAIN_BARCODE, NATURE_ID, NATURE_DESC, TRADE_ID, TRADE_DESC, QTY_STORE_01, QTY_STORE_02, QTY_STORE_05, QTY_STORE_06, QTY_STORE_07, QTY_STORE_08, QTY_STORE_10, QTY_STORE_11, QTY_STORE_12, QTY_STORE_19, QTY_STORE_21, QTY_STORE_23, QTY_STORE_31, QTY_STORE_32, QTY_STORE_33, QTY_STORE_34, QTY_STORE_35, SALE_PRICE_NOTAX_STORE_01, SALE_PRICE_NOTAX_STORE_02, SALE_PRICE_NOTAX_STORE_05, SALE_PRICE_NOTAX_STORE_06, SALE_PRICE_NOTAX_STORE_08, SALE_PRICE_NOTAX_STORE_07, SALE_PRICE_NOTAX_STORE_31, SALE_PRICE_NOTAX_STORE_32, SALE_PRICE_NOTAX_STORE_33, SALE_PRICE_NOTAX_STORE_34, SALE_PRICE_NOTAX_STORE_35, FIRST_DISC_PER_STORE_01, FIRST_DISC_PER_STORE_02, FIRST_DISC_PER_STORE_05, FIRST_DISC_PER_STORE_06, FIRST_DISC_PER_STORE_07, FIRST_DISC_PER_STORE_08, FIRST_DISC_PER_STORE_31, FIRST_DISC_PER_STORE_32, FIRST_DISC_PER_STORE_33, FIRST_DISC_PER_STORE_34, FIRST_DISC_PER_STORE_35, SECOND_DISC_PER_STORE_01, SECOND_DISC_PER_STORE_02, SECOND_DISC_PER_STORE_05, SECOND_DISC_PER_STORE_06, SECOND_DISC_PER_STORE_07, SECOND_DISC_PER_STORE_08, SECOND_DISC_PER_STORE_31, SECOND_DISC_PER_STORE_32, SECOND_DISC_PER_STORE_33, SECOND_DISC_PER_STORE_34, SECOND_DISC_PER_STORE_35 */

    // Store start time
    let start = Instant::now();

    let mut stmt;
    let rows;
    if my_p_ref == "%" && my_p_barcode != "%" {
        println!("a");
        stmt = conn.statement("SELECT ITEM_ID, IS_ACTIVE_CARD, CAN_BE_SOLD, ITEM_DESC, ITEM_DESC_S, FOREIGN_ITEM_CODE, ITEM_CAT, ITEM_SUB_CAT, SALE_UNIT, UNIT_DESC, PACKING, CARD_OPEN_DATE, HS_CODE, COUNTRY, COUNTRY_DESC, SUPPLIER_ID, SUPPLIER_DESC, ITEM_MAIN_BARCODE, NATURE_ID, NATURE_DESC, TRADE_ID, TRADE_DESC, QTY_STORE_01, QTY_STORE_02, QTY_STORE_05, QTY_STORE_06, QTY_STORE_07, QTY_STORE_08, QTY_STORE_09, QTY_STORE_10, QTY_STORE_11, QTY_STORE_12, QTY_STORE_19, QTY_STORE_21, QTY_STORE_23, QTY_STORE_31, QTY_STORE_32, QTY_STORE_33, QTY_STORE_34, QTY_STORE_35, SALE_PRICE_NOTAX_STORE_01, SALE_PRICE_NOTAX_STORE_02, SALE_PRICE_NOTAX_STORE_05, SALE_PRICE_NOTAX_STORE_06, SALE_PRICE_NOTAX_STORE_08, SALE_PRICE_NOTAX_STORE_09, SALE_PRICE_NOTAX_STORE_07, SALE_PRICE_NOTAX_STORE_31, SALE_PRICE_NOTAX_STORE_32, SALE_PRICE_NOTAX_STORE_33, SALE_PRICE_NOTAX_STORE_34, SALE_PRICE_NOTAX_STORE_35, FIRST_DISC_PER_STORE_01, FIRST_DISC_PER_STORE_02, FIRST_DISC_PER_STORE_05, FIRST_DISC_PER_STORE_06, FIRST_DISC_PER_STORE_07, FIRST_DISC_PER_STORE_08, FIRST_DISC_PER_STORE_09, FIRST_DISC_PER_STORE_31, FIRST_DISC_PER_STORE_32, FIRST_DISC_PER_STORE_33, FIRST_DISC_PER_STORE_34, FIRST_DISC_PER_STORE_35, SECOND_DISC_PER_STORE_01, SECOND_DISC_PER_STORE_02, SECOND_DISC_PER_STORE_05, SECOND_DISC_PER_STORE_06, SECOND_DISC_PER_STORE_07, SECOND_DISC_PER_STORE_08, SECOND_DISC_PER_STORE_09, SECOND_DISC_PER_STORE_31, SECOND_DISC_PER_STORE_32, SECOND_DISC_PER_STORE_33, SECOND_DISC_PER_STORE_34, SECOND_DISC_PER_STORE_35 FROM ODBC_JHC.JHC_INVDATA_PI WHERE BARCODE_LISTED LIKE '%' || :barcode || '%' AND ITEM_ID LIKE :id").build()?;
        rows = stmt.query(&[&my_p_barcode, &my_p_id])?;
    } else if my_p_ref != "%" && my_p_barcode == "%" {
        println!("b");
        stmt = conn.statement("SELECT ITEM_ID, IS_ACTIVE_CARD, CAN_BE_SOLD, ITEM_DESC, ITEM_DESC_S, FOREIGN_ITEM_CODE, ITEM_CAT, ITEM_SUB_CAT, SALE_UNIT, UNIT_DESC, PACKING, CARD_OPEN_DATE, HS_CODE, COUNTRY, COUNTRY_DESC, SUPPLIER_ID, SUPPLIER_DESC, ITEM_MAIN_BARCODE, NATURE_ID, NATURE_DESC, TRADE_ID, TRADE_DESC, QTY_STORE_01, QTY_STORE_02, QTY_STORE_05, QTY_STORE_06, QTY_STORE_07, QTY_STORE_08, QTY_STORE_09, QTY_STORE_10, QTY_STORE_11, QTY_STORE_12, QTY_STORE_19, QTY_STORE_21, QTY_STORE_23, QTY_STORE_31, QTY_STORE_32, QTY_STORE_33, QTY_STORE_34, QTY_STORE_35, SALE_PRICE_NOTAX_STORE_01, SALE_PRICE_NOTAX_STORE_02, SALE_PRICE_NOTAX_STORE_05, SALE_PRICE_NOTAX_STORE_06, SALE_PRICE_NOTAX_STORE_08, SALE_PRICE_NOTAX_STORE_09, SALE_PRICE_NOTAX_STORE_07, SALE_PRICE_NOTAX_STORE_31, SALE_PRICE_NOTAX_STORE_32, SALE_PRICE_NOTAX_STORE_33, SALE_PRICE_NOTAX_STORE_34, SALE_PRICE_NOTAX_STORE_35, FIRST_DISC_PER_STORE_01, FIRST_DISC_PER_STORE_02, FIRST_DISC_PER_STORE_05, FIRST_DISC_PER_STORE_06, FIRST_DISC_PER_STORE_07, FIRST_DISC_PER_STORE_08, FIRST_DISC_PER_STORE_09, FIRST_DISC_PER_STORE_31, FIRST_DISC_PER_STORE_32, FIRST_DISC_PER_STORE_33, FIRST_DISC_PER_STORE_34, FIRST_DISC_PER_STORE_35, SECOND_DISC_PER_STORE_01, SECOND_DISC_PER_STORE_02, SECOND_DISC_PER_STORE_05, SECOND_DISC_PER_STORE_06, SECOND_DISC_PER_STORE_07, SECOND_DISC_PER_STORE_08, SECOND_DISC_PER_STORE_09, SECOND_DISC_PER_STORE_31, SECOND_DISC_PER_STORE_32, SECOND_DISC_PER_STORE_33, SECOND_DISC_PER_STORE_34, SECOND_DISC_PER_STORE_35 FROM ODBC_JHC.JHC_INVDATA_PI WHERE FOREIGN_ITEM_CODE LIKE :ref AND ITEM_ID LIKE :id").build()?;
        rows = stmt.query(&[&my_p_ref, &my_p_id])?;
    } else if my_p_ref == "%" && my_p_barcode == "%" {
        println!("c");
        stmt = conn.statement("SELECT ITEM_ID, IS_ACTIVE_CARD, CAN_BE_SOLD, ITEM_DESC, ITEM_DESC_S, FOREIGN_ITEM_CODE, ITEM_CAT, ITEM_SUB_CAT, SALE_UNIT, UNIT_DESC, PACKING, CARD_OPEN_DATE, HS_CODE, COUNTRY, COUNTRY_DESC, SUPPLIER_ID, SUPPLIER_DESC, ITEM_MAIN_BARCODE, NATURE_ID, NATURE_DESC, TRADE_ID, TRADE_DESC, QTY_STORE_01, QTY_STORE_02, QTY_STORE_05, QTY_STORE_06, QTY_STORE_07, QTY_STORE_08, QTY_STORE_09, QTY_STORE_10, QTY_STORE_11, QTY_STORE_12, QTY_STORE_19, QTY_STORE_21, QTY_STORE_23, QTY_STORE_31, QTY_STORE_32, QTY_STORE_33, QTY_STORE_34, QTY_STORE_35, SALE_PRICE_NOTAX_STORE_01, SALE_PRICE_NOTAX_STORE_02, SALE_PRICE_NOTAX_STORE_05, SALE_PRICE_NOTAX_STORE_06, SALE_PRICE_NOTAX_STORE_08, SALE_PRICE_NOTAX_STORE_09, SALE_PRICE_NOTAX_STORE_07, SALE_PRICE_NOTAX_STORE_31, SALE_PRICE_NOTAX_STORE_32, SALE_PRICE_NOTAX_STORE_33, SALE_PRICE_NOTAX_STORE_34, SALE_PRICE_NOTAX_STORE_35, FIRST_DISC_PER_STORE_01, FIRST_DISC_PER_STORE_02, FIRST_DISC_PER_STORE_05, FIRST_DISC_PER_STORE_06, FIRST_DISC_PER_STORE_07, FIRST_DISC_PER_STORE_08, FIRST_DISC_PER_STORE_09, FIRST_DISC_PER_STORE_31, FIRST_DISC_PER_STORE_32, FIRST_DISC_PER_STORE_33, FIRST_DISC_PER_STORE_34, FIRST_DISC_PER_STORE_35, SECOND_DISC_PER_STORE_01, SECOND_DISC_PER_STORE_02, SECOND_DISC_PER_STORE_05, SECOND_DISC_PER_STORE_06, SECOND_DISC_PER_STORE_07, SECOND_DISC_PER_STORE_08, SECOND_DISC_PER_STORE_09, SECOND_DISC_PER_STORE_31, SECOND_DISC_PER_STORE_32, SECOND_DISC_PER_STORE_33, SECOND_DISC_PER_STORE_34, SECOND_DISC_PER_STORE_35 FROM ODBC_JHC.JHC_INVDATA_PI WHERE ITEM_ID LIKE :id").build()?;
        rows = stmt.query(&[&my_p_id])?;
    } else {
        println!("d");
        stmt = conn.statement("SELECT ITEM_ID, IS_ACTIVE_CARD, CAN_BE_SOLD, ITEM_DESC, ITEM_DESC_S, FOREIGN_ITEM_CODE, ITEM_CAT, ITEM_SUB_CAT, SALE_UNIT, UNIT_DESC, PACKING, CARD_OPEN_DATE, HS_CODE, COUNTRY, COUNTRY_DESC, SUPPLIER_ID, SUPPLIER_DESC, ITEM_MAIN_BARCODE, NATURE_ID, NATURE_DESC, TRADE_ID, TRADE_DESC, QTY_STORE_01, QTY_STORE_02, QTY_STORE_05, QTY_STORE_06, QTY_STORE_07, QTY_STORE_08, QTY_STORE_09, QTY_STORE_10, QTY_STORE_11, QTY_STORE_12, QTY_STORE_19, QTY_STORE_21, QTY_STORE_23, QTY_STORE_31, QTY_STORE_32, QTY_STORE_33, QTY_STORE_34, QTY_STORE_35, SALE_PRICE_NOTAX_STORE_01, SALE_PRICE_NOTAX_STORE_02, SALE_PRICE_NOTAX_STORE_05, SALE_PRICE_NOTAX_STORE_06, SALE_PRICE_NOTAX_STORE_08, SALE_PRICE_NOTAX_STORE_09, SALE_PRICE_NOTAX_STORE_07, SALE_PRICE_NOTAX_STORE_31, SALE_PRICE_NOTAX_STORE_32, SALE_PRICE_NOTAX_STORE_33, SALE_PRICE_NOTAX_STORE_34, SALE_PRICE_NOTAX_STORE_35, FIRST_DISC_PER_STORE_01, FIRST_DISC_PER_STORE_02, FIRST_DISC_PER_STORE_05, FIRST_DISC_PER_STORE_06, FIRST_DISC_PER_STORE_07, FIRST_DISC_PER_STORE_08, FIRST_DISC_PER_STORE_09, FIRST_DISC_PER_STORE_31, FIRST_DISC_PER_STORE_32, FIRST_DISC_PER_STORE_33, FIRST_DISC_PER_STORE_34, FIRST_DISC_PER_STORE_35, SECOND_DISC_PER_STORE_01, SECOND_DISC_PER_STORE_02, SECOND_DISC_PER_STORE_05, SECOND_DISC_PER_STORE_06, SECOND_DISC_PER_STORE_07, SECOND_DISC_PER_STORE_08, SECOND_DISC_PER_STORE_09, SECOND_DISC_PER_STORE_31, SECOND_DISC_PER_STORE_32, SECOND_DISC_PER_STORE_33, SECOND_DISC_PER_STORE_34, SECOND_DISC_PER_STORE_35 FROM ODBC_JHC.JHC_INVDATA_PI WHERE FOREIGN_ITEM_CODE LIKE :ref AND BARCODE_LISTED LIKE '%' || :barcode || '%' AND ITEM_ID LIKE :id").build()?;
        rows = stmt.query(&[&my_p_ref, &my_p_barcode, &my_p_id])?;
    }

    // let mut stmt = conn.statement("SELECT ITEM_ID, IS_ACTIVE, CAN_BE_SOLD, ITEM_DESC, ITEM_DESC_S, FOREIGN_ITEM_CODE, ITEM_CAT, ITEM_SUB_CAT, SALE_UNIT, UNIT_DESC, PACKING, CARD_OPEN_DATE, HS_CODE, COUNTRY, COUNTRY_DESC, SUPPLIER_ID, SUPPLIER_DESC, ITEM_MAIN_BARCODE, NATURE_ID, NATURE_DESC, TRADE_ID, TRADE_DESC, QTY_STORE_01, QTY_STORE_02, QTY_STORE_05, QTY_STORE_06, QTY_STORE_07, QTY_STORE_08, QTY_STORE_09, QTY_STORE_10, QTY_STORE_11, QTY_STORE_12, QTY_STORE_19, QTY_STORE_21, QTY_STORE_23, QTY_STORE_31, QTY_STORE_32, QTY_STORE_33, QTY_STORE_34, QTY_STORE_35, SALE_PRICE_NOTAX_STORE_01, SALE_PRICE_NOTAX_STORE_02, SALE_PRICE_NOTAX_STORE_05, SALE_PRICE_NOTAX_STORE_06, SALE_PRICE_NOTAX_STORE_08, SALE_PRICE_NOTAX_STORE_09, SALE_PRICE_NOTAX_STORE_07, SALE_PRICE_NOTAX_STORE_31, SALE_PRICE_NOTAX_STORE_32, SALE_PRICE_NOTAX_STORE_33, SALE_PRICE_NOTAX_STORE_34, SALE_PRICE_NOTAX_STORE_35, FIRST_DISC_PER_STORE_01, FIRST_DISC_PER_STORE_02, FIRST_DISC_PER_STORE_05, FIRST_DISC_PER_STORE_06, FIRST_DISC_PER_STORE_07, FIRST_DISC_PER_STORE_08, FIRST_DISC_PER_STORE_09, FIRST_DISC_PER_STORE_31, FIRST_DISC_PER_STORE_32, FIRST_DISC_PER_STORE_33, FIRST_DISC_PER_STORE_34, FIRST_DISC_PER_STORE_35, SECOND_DISC_PER_STORE_01, SECOND_DISC_PER_STORE_02, SECOND_DISC_PER_STORE_05, SECOND_DISC_PER_STORE_06, SECOND_DISC_PER_STORE_07, SECOND_DISC_PER_STORE_08, SECOND_DISC_PER_STORE_09, SECOND_DISC_PER_STORE_31, SECOND_DISC_PER_STORE_32, SECOND_DISC_PER_STORE_33, SECOND_DISC_PER_STORE_34, SECOND_DISC_PER_STORE_35, T_AVE_COST FROM ODBC_JHC.JHC_INVDATA WHERE FOREIGN_ITEM_CODE LIKE :ref AND ITEM_MAIN_BARCODE LIKE :barcode AND ITEM_ID LIKE :id").build()?;
    //let mut stmt = conn.statement("SELECT ITEM_ID, IS_ACTIVE, CAN_BE_SOLD, ITEM_DESC, ITEM_DESC_S, FOREIGN_ITEM_CODE, ITEM_CAT, ITEM_SUB_CAT, SALE_UNIT, UNIT_DESC, PACKING, CARD_OPEN_DATE, HS_CODE, COUNTRY, COUNTRY_DESC, SUPPLIER_ID, SUPPLIER_DESC, ITEM_MAIN_BARCODE, NATURE_ID, NATURE_DESC, TRADE_ID, TRADE_DESC, QTY_STORE_01, QTY_STORE_02, QTY_STORE_05, QTY_STORE_06, QTY_STORE_07, QTY_STORE_08, QTY_STORE_09, QTY_STORE_10, QTY_STORE_11, QTY_STORE_12, QTY_STORE_19, QTY_STORE_21, QTY_STORE_23, QTY_STORE_31, QTY_STORE_32, QTY_STORE_33, QTY_STORE_34, QTY_STORE_35, SALE_PRICE_NOTAX_STORE_01, SALE_PRICE_NOTAX_STORE_02, SALE_PRICE_NOTAX_STORE_05, SALE_PRICE_NOTAX_STORE_06, SALE_PRICE_NOTAX_STORE_08, SALE_PRICE_NOTAX_STORE_09, SALE_PRICE_NOTAX_STORE_07, SALE_PRICE_NOTAX_STORE_31, SALE_PRICE_NOTAX_STORE_32, SALE_PRICE_NOTAX_STORE_33, SALE_PRICE_NOTAX_STORE_34, SALE_PRICE_NOTAX_STORE_35, FIRST_DISC_PER_STORE_01, FIRST_DISC_PER_STORE_02, FIRST_DISC_PER_STORE_05, FIRST_DISC_PER_STORE_06, FIRST_DISC_PER_STORE_07, FIRST_DISC_PER_STORE_08, FIRST_DISC_PER_STORE_09, FIRST_DISC_PER_STORE_31, FIRST_DISC_PER_STORE_32, FIRST_DISC_PER_STORE_33, FIRST_DISC_PER_STORE_34, FIRST_DISC_PER_STORE_35, SECOND_DISC_PER_STORE_01, SECOND_DISC_PER_STORE_02, SECOND_DISC_PER_STORE_05, SECOND_DISC_PER_STORE_06, SECOND_DISC_PER_STORE_07, SECOND_DISC_PER_STORE_08, SECOND_DISC_PER_STORE_09, SECOND_DISC_PER_STORE_31, SECOND_DISC_PER_STORE_32, SECOND_DISC_PER_STORE_33, SECOND_DISC_PER_STORE_34, SECOND_DISC_PER_STORE_35, T_AVE_COST FROM ODBC_JHC.JHC_INVDATA WHERE FOREIGN_ITEM_CODE LIKE :ref AND (ITEM_MAIN_BARCODE = :barcode OR BARCODE_LISTED LIKE '%' || :barcode || '%') AND ITEM_ID LIKE :id").build()?;

    println!("Query Time: {:?}", start.elapsed());

    let mut products: Vec<Product> = vec![];

    for row_result in rows {
        let row = row_result?;
        products.push(Product {
            ITEM_ID: row.get("ITEM_ID")?,
            IS_ACTIVE: row.get("IS_ACTIVE_CARD")?,
            CAN_BE_SOLD: row.get("CAN_BE_SOLD")?,
            ITEM_DESC: row.get("ITEM_DESC")?,
            ITEM_DESC_S: row.get("ITEM_DESC_S")?,
            FOREIGN_ITEM_CODE: row.get("FOREIGN_ITEM_CODE")?,
            ITEM_CAT: row.get("ITEM_CAT")?,
            ITEM_SUB_CAT: row.get("ITEM_SUB_CAT")?,
            SALE_UNIT: row.get("SALE_UNIT")?,
            UNIT_DESC: row.get("UNIT_DESC")?,
            PACKING: row.get("PACKING")?,
            CARD_OPEN_DATE: row.get("CARD_OPEN_DATE")?,
            HS_CODE: row.get("HS_CODE")?,
            COUNTRY: row.get("COUNTRY")?,
            COUNTRY_DESC: row.get("COUNTRY_DESC")?,
            SUPPLIER_ID: row.get("SUPPLIER_ID")?,
            SUPPLIER_DESC: row.get("SUPPLIER_DESC")?,
            ITEM_MAIN_BARCODE: row.get("ITEM_MAIN_BARCODE")?,
            NATURE_ID: row.get("NATURE_ID")?,
            NATURE_DESC: row.get("NATURE_DESC")?,
            TRADE_ID: row.get("TRADE_ID")?,
            TRADE_DESC: row.get("TRADE_DESC")?,
            QTY_STORE_01: row.get("QTY_STORE_01")?,
            QTY_STORE_02: row.get("QTY_STORE_02")?,
            QTY_STORE_05: row.get("QTY_STORE_05")?,
            QTY_STORE_06: row.get("QTY_STORE_06")?,
            QTY_STORE_07: row.get("QTY_STORE_07")?,
            QTY_STORE_08: row.get("QTY_STORE_08")?,
            QTY_STORE_09: row.get("QTY_STORE_09")?,
            QTY_STORE_10: row.get("QTY_STORE_10")?,
            QTY_STORE_11: row.get("QTY_STORE_11")?,
            QTY_STORE_12: row.get("QTY_STORE_12")?,
            QTY_STORE_19: row.get("QTY_STORE_19")?,
            QTY_STORE_21: row.get("QTY_STORE_21")?,
            QTY_STORE_23: row.get("QTY_STORE_23")?,
            QTY_STORE_31: row.get("QTY_STORE_31")?,
            QTY_STORE_32: row.get("QTY_STORE_32")?,
            QTY_STORE_33: row.get("QTY_STORE_33")?,
            QTY_STORE_34: row.get("QTY_STORE_34")?,
            QTY_STORE_35: row.get("QTY_STORE_35")?,
            SALE_PRICE_NOTAX_STORE_01: row.get("SALE_PRICE_NOTAX_STORE_01")?,
            SALE_PRICE_NOTAX_STORE_02: row.get("SALE_PRICE_NOTAX_STORE_02")?,
            SALE_PRICE_NOTAX_STORE_05: row.get("SALE_PRICE_NOTAX_STORE_05")?,
            SALE_PRICE_NOTAX_STORE_06: row.get("SALE_PRICE_NOTAX_STORE_06")?,
            SALE_PRICE_NOTAX_STORE_08: row.get("SALE_PRICE_NOTAX_STORE_08")?,
            SALE_PRICE_NOTAX_STORE_09: row.get("SALE_PRICE_NOTAX_STORE_09")?,
            SALE_PRICE_NOTAX_STORE_07: row.get("SALE_PRICE_NOTAX_STORE_07")?,
            SALE_PRICE_NOTAX_STORE_31: row.get("SALE_PRICE_NOTAX_STORE_31")?,
            SALE_PRICE_NOTAX_STORE_32: row.get("SALE_PRICE_NOTAX_STORE_32")?,
            SALE_PRICE_NOTAX_STORE_33: row.get("SALE_PRICE_NOTAX_STORE_33")?,
            SALE_PRICE_NOTAX_STORE_34: row.get("SALE_PRICE_NOTAX_STORE_34")?,
            SALE_PRICE_NOTAX_STORE_35: row.get("SALE_PRICE_NOTAX_STORE_35")?,
            FIRST_DISC_PER_STORE_01: row.get("FIRST_DISC_PER_STORE_01")?,
            FIRST_DISC_PER_STORE_02: row.get("FIRST_DISC_PER_STORE_02")?,
            FIRST_DISC_PER_STORE_05: row.get("FIRST_DISC_PER_STORE_05")?,
            FIRST_DISC_PER_STORE_06: row.get("FIRST_DISC_PER_STORE_06")?,
            FIRST_DISC_PER_STORE_07: row.get("FIRST_DISC_PER_STORE_07")?,
            FIRST_DISC_PER_STORE_08: row.get("FIRST_DISC_PER_STORE_08")?,
            FIRST_DISC_PER_STORE_09: row.get("FIRST_DISC_PER_STORE_09")?,
            FIRST_DISC_PER_STORE_31: row.get("FIRST_DISC_PER_STORE_31")?,
            FIRST_DISC_PER_STORE_32: row.get("FIRST_DISC_PER_STORE_32")?,
            FIRST_DISC_PER_STORE_33: row.get("FIRST_DISC_PER_STORE_33")?,
            FIRST_DISC_PER_STORE_34: row.get("FIRST_DISC_PER_STORE_34")?,
            FIRST_DISC_PER_STORE_35: row.get("FIRST_DISC_PER_STORE_35")?,
            SECOND_DISC_PER_STORE_01: row.get("SECOND_DISC_PER_STORE_01")?,
            SECOND_DISC_PER_STORE_02: row.get("SECOND_DISC_PER_STORE_02")?,
            SECOND_DISC_PER_STORE_05: row.get("SECOND_DISC_PER_STORE_05")?,
            SECOND_DISC_PER_STORE_06: row.get("SECOND_DISC_PER_STORE_06")?,
            SECOND_DISC_PER_STORE_07: row.get("SECOND_DISC_PER_STORE_07")?,
            SECOND_DISC_PER_STORE_08: row.get("SECOND_DISC_PER_STORE_08")?,
            SECOND_DISC_PER_STORE_09: row.get("SECOND_DISC_PER_STORE_09")?,
            SECOND_DISC_PER_STORE_31: row.get("SECOND_DISC_PER_STORE_31")?,
            SECOND_DISC_PER_STORE_32: row.get("SECOND_DISC_PER_STORE_32")?,
            SECOND_DISC_PER_STORE_33: row.get("SECOND_DISC_PER_STORE_33")?,
            SECOND_DISC_PER_STORE_34: row.get("SECOND_DISC_PER_STORE_34")?,
            SECOND_DISC_PER_STORE_35: row.get("SECOND_DISC_PER_STORE_35")?,
            T_AVE_COST: None
        });
    }

    info!("Products Count: {:?}", products.len());

    Ok(products)
}
*/